--
-- DO NOT EDIT THIS FILE !
--
local fpairs, fileFind = pairs, file.Find
local _includeEx =
	function( path )
		local files, directories = fileFind( path .. "/*", "LUA", "nameasc" )
		for k, v in fpairs( files ) do
			if ( v:GetExtensionFromFilename():lower() == "lua" ) then
				include( path .. '/' .. v )
			end
		end
		for k, v in fpairs( directories ) do
			if ( v != ".." && v != '.' ) then
				includeEx( path .. '/' .. v )
			end
		end
	end
includeEx = _includeEx